<?php
$limit = Mage::getStoreConfig('tr_section_setttings/crosssell/cross_sell_page_items');
$collection = $this->getCrossSellingItemsByOrderId($this->getData('orderId'), $limit);
$count = count($collection);
?>
<?php if($count): ?>
    <div class="trtrack-crosssell">
        <h2><?php echo $this->__('you may be interested in the following items:') ?></h2>
        <ul class="trtrack-products-grid trtrack-products-grid--col-<?php echo $count ?>">
            <?php foreach ($collection as $_item): ?>
                <li>
                    <div class="trtrack-list-info-box-wrap">
                        <div class="trtrack-list-info-box">
                            <a class="trtrack-product-image" target="_blank" href="<?php echo $_item->getProductUrl() ?>" title="<?php echo $this->escapeHtml($_item->getName()) ?>">
                                <img src="<?php echo $this->helper('catalog/image')->init($_item, 'small_image')->resize(null, 150); ?>" alt="<?php echo $this->escapeHtml($_item->getName()) ?>" />
                            </a>
                            <h3 class="trtrack-product-name"><a href="<?php echo $_item->getProductUrl() ?>"><?php echo $this->escapeHtml($_item->getName()) ?></a></h3>
                            <?php echo $this->getPriceHtml($_item, true) ?>
                        </div>
                    </div>
                    <button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_item) ?>')"><span><span><?php echo $this->__('Add to Cart') ?></span></span></button>
                </li>
            <?php endforeach; ?>
        </ul>
    </div>
	<script type="text/javascript">
        function fixCrossBoxes() {
            var max = 0;
            $(".trtrack-list-info-box").each(function () {
                max = Math.max(max, $(this).height());
            });
            $(".trtrack-list-info-box-wrap").each(function () {
                $(this).css(
                    "height", max + 'px'
                );
            });
        }
        window.onresize = function(event) {
            fixCrossBoxes();
        };
        $(document).ready(function(){
		     fixCrossBoxes();
        })

    </script>
   
<?php endif; ?>
