<div style="padding-top: 35px;">
    <div class="container">
        <div class="row">
            <div class="col-sm-12">
                <h2 class="filter-title"><span class="content"><strong>Daily Deals</strong></span></h2>
                <div id="featured_product" class="owl-top-narrow">
                    <?php echo $this->getLayout()->createBlock('filterproducts/featured_home_list')->setTemplate('filterproducts/list.phtml')->tohtml(); ?>
                </div>
                <script type="text/javascript">
                    jQuery(function($){
                        $("#featured_product .filter-products .owl-carousel").owlCarousel({lazyLoad: true,    itemsCustom: [ [0, 1], [320, 1], [480, 2], [768, 3], [992, 4], [1280, 5] ],    responsiveRefreshRate: 50,    slideSpeed: 200,    paginationSpeed: 500,    scrollPerPage: false,    stopOnHover: true,    rewindNav: true,    rewindSpeed: 600,    pagination: false,    navigation: true,    autoPlay: true,    navigationText:["<i class='icon-left-open'></i>","<i class='icon-right-open'></i>"]});
                    });
                </script>
            </div>
        </div>
    </div>
</div>