<div class="single-images border-radius">
        <div class="row">
            <div class="col-sm-3 col-xs-6">
                <a class="image-link" href="#"><h1>Shoes</h1>
                    <img src="https://s11.postimg.org/djh14i0xf/Capture.png"  alt="" />
                </a>
            </div>
            <div class="col-sm-3 col-xs-6" style="padding-left:5px;">
                <a class="image-link" href="#"><h1>Caps</h1>
                    <img src="https://s11.postimg.org/5f8wzreib/hat.png" alt="" />
                </a>
            </div>
            <div class="col-sm-3 col-xs-6" >
                <a class="image-link" href="#"><h1>Hoodies</h1>
                    <img src="https://s11.postimg.org/904sizj1v/hoodie.png" alt="" />
                </a>
            </div>
            <div class="col-sm-3 col-xs-6" style="padding-left:5px;">
                <a class="image-link" href="#"><h1>Jeans</h1>
                    <img src="https://s11.postimg.org/k0zxo0bar/woman.png" alt="" />
                </a>
            </div>
        </div>
</div>