<div class="homepage-bar">
    <div class="container">
        <div class="row">
            <div class="col-md-4">
                <i class="icon-truck" style="font-size:36px;"></i><div class="text-area"><h3>FREE SHIPPING & RETURN</h3><p>Free shipping on all orders over $99.</p></div>
            </div>
            <div class="col-md-4">
                <i class="icon-dollar"></i><div class="text-area"><h3>MONEY BACK GUARANTEE</h3><p>100% money back guarantee.</p></div>
            </div>
            <div class="col-md-4">
                <i class="icon-lifebuoy" style="font-size:32px;"></i><div class="text-area"><h3>ONLINE SUPPORT 24/7</h3><p>Lorem ipsum dolor sit amet.</p></div>
            </div>
        </div>
    </div>
</div>