<div class="single-images border-radius">
        <div class="row">
            <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">
                <a class="image-link" href="#">
                    <img src="https://s11.postimg.org/djrwqxypv/shoes.png" alt="" />
                </a>
            </div>
            <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12" >
                <a class="image-link" href="#">
                    <img src="https://s11.postimg.org/oi3694nb7/board.png" alt="" />
                </a>
            </div>
        </div>
</div>